import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ul className="navbar">
            <a href="/">Channel 1</a>
            <a href='/'>Channel 2</a>
            <a href='/'>Channel 3</a>
        </ul> 
        {children}
      </body>
    </html>
  )
}
